# Generated by Django 4.0.1 on 2022-01-31 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_city_options_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, verbose_name='Номер класса')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school', verbose_name='Буква класса')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_exp', models.CharField(max_length=50, verbose_name='Стаж работы')),
                ('achievement', models.CharField(max_length=500, verbose_name='Достижения')),
                ('about', models.CharField(max_length=150, verbose_name='О учителе')),
                ('is_boss', models.BooleanField(default=False)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.schoolclass', verbose_name='Класс.рук')),
                ('subject', models.ManyToManyField(blank=True, to='myschool.Subject', verbose_name='Преподаваемые предметы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('date_add', models.DateField(verbose_name='Дата поступления')),
                ('date_end', models.DateField(verbose_name='Дата выпуска')),
                ('amount_hold_back', models.BinaryField(editable=True, verbose_name='Количество оставлений на второй год')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.schoolclass', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('student', models.ManyToManyField(to='myschool.Student', verbose_name='Ребёнок')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оценки')),
                ('mark', models.CharField(max_length=1, verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.teacher', verbose_name='Учитель')),
            ],
        ),
    ]
