# Generated by Django 4.0.1 on 2022-02-10 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_city_options_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название д/з')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Текст д/з')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата выкладывания д/з')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата завершения приема работ')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, verbose_name='Номер класса')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school', verbose_name='Буква класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_exp', models.CharField(blank=True, max_length=50, verbose_name='Стаж работы')),
                ('achievement', models.CharField(blank=True, max_length=500, verbose_name='Достижения')),
                ('about', models.CharField(blank=True, max_length=150, verbose_name='О учителе')),
                ('is_boss', models.BooleanField(default=False)),
                ('school_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myschool.schoolclass', verbose_name='Класс.рук')),
                ('subject', models.ManyToManyField(blank=True, to='myschool.Subject', verbose_name='Преподаваемые предметы')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('date_add', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('amount_hold_back', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Количество оставлений на второй год')),
                ('school_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myschool.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('student', models.ManyToManyField(to='myschool.Student', verbose_name='Ребёнок')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оценки')),
                ('mark', models.CharField(max_length=1, verbose_name='Оценка')),
                ('description', models.CharField(max_length=150, null=True, verbose_name='Примечание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на файл с решением')),
                ('text_solution', models.CharField(max_length=500, verbose_name='Примечание')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Выполнено?')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивировано?')),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myschool.homework', verbose_name='Домашнее задание')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myschool.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Домашнее задание для ученика',
                'verbose_name_plural': 'Домашние задания для ученика',
                'ordering': ['homework'],
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.schoolclass', verbose_name='Кому задана?'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject', verbose_name='По какому предмету д/з'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.teacher', verbose_name='Кто задал?'),
        ),
    ]
