# Generated by Django 4.0.1 on 2022-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkforstudent',
            name='mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
